### PR TITLE
Several fixes and enhancements

### PR DESCRIPTION
**Pull request by davehunt**
Lots of changes here, sorry for the big patch! I've addressed #13 and #21. It also makes #17 obsolete. Also a few new tests, and documentation!

### CODE REVIEW

**Comment by davehunt** [comment]
It looks like there's an issue with pytest-xdist. I'll see if I can work out a fix.

**Comment by davehunt** [comment]
I've added a workaround for the pytest-xdist issue, so I think this is good to go.

**Comment by davehunt** [comment]
> Hi @davehunt, today is the day! I have big troubles to review your changes, since you mixed renames with changes. Therefore I will repeat your changes on a branch, but separate the rename part into a separate commit (and maybe split some more changes into commits). Please use smaller commits in the future. ;)

Sorry about that, one improvement led to another. I'm often on the other side, so appreciate that it can be difficult to review. Let me know if you need any help.

**Comment by florianpilz** [comment]
@davehunt Why did you choose the Mozilla Public License?

**Comment by florianpilz** [comment]
@klrmn Is it OK for you to put this project under the MIT license, which is used by `pytest` itself? Your are the author of the code, so it's your Copyright we are talking about.

**Comment by florianpilz** [comment]
@davehunt @klrmn Ah, found the license declaration in `setup.py`. That clears things up.

**Comment by florianpilz** [comment]
@davehunt I just released a new version on PyPI https://pypi.python.org/pypi/pytest-rerunfailures/1.0.0

**Comment by davehunt** [comment]
Excellent, thank you! :smile:

**Comment by klrmn** [comment]
I don't really have a strong opinion about which license (altho I probably
should). I just chose MPL because I was working with Mozilla at the time.

**Pull request merged**
